# Generated by Django 2.1.2 on 2019-01-14 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("scratchtester", "0002_auto_20190114_1603")]

    operations = [
        migrations.CreateModel(
            name="CsvStructure",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("html", models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name="measurement",
            name="name",
            field=models.CharField(default="new_measurment", max_length=20),
        ),
        migrations.AddField(
            model_name="measurement",
            name="raw_structure",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="scratchtester.CsvStructure",
            ),
        ),
    ]
