# Generated by Django 2.1.2 on 2019-01-14 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("scratchtester", "0003_auto_20190114_1737")]

    operations = [
        migrations.AddField(
            model_name="measurement",
            name="options",
            field=models.CharField(default="{}", max_length=400),
        ),
        migrations.AlterField(
            model_name="csvstructure",
            name="html",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="measurement",
            name="raw_structure",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="scratchtester.CsvStructure",
            ),
        ),
    ]
