# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scratchtester.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(815, 754)
        self.mainWidget = QtWidgets.QWidget(MainWindow)
        self.mainWidget.setObjectName("mainWidget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.mainWidget)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.tabWidget = QtWidgets.QTabWidget(self.mainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.raw_data_tab = QtWidgets.QWidget()
        self.raw_data_tab.setObjectName("raw_data_tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.raw_data_tab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget = QtWidgets.QWidget(self.raw_data_tab)
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.raw_properties = QtWidgets.QWidget(self.widget)
        self.raw_properties.setObjectName("raw_properties")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.raw_properties)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.raw_file_path = QtWidgets.QLineEdit(self.raw_properties)
        self.raw_file_path.setMinimumSize(QtCore.QSize(400, 20))
        self.raw_file_path.setObjectName("raw_file_path")
        self.horizontalLayout_3.addWidget(self.raw_file_path)
        self.raw_load_button = QtWidgets.QPushButton(self.raw_properties)
        self.raw_load_button.setObjectName("raw_load_button")
        self.horizontalLayout_3.addWidget(self.raw_load_button)
        self.raw_search_button = QtWidgets.QPushButton(self.raw_properties)
        self.raw_search_button.setObjectName("raw_search_button")
        self.horizontalLayout_3.addWidget(self.raw_search_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.raw_data_struc = QtWidgets.QComboBox(self.raw_properties)
        self.raw_data_struc.setObjectName("raw_data_struc")
        self.horizontalLayout_4.addWidget(self.raw_data_struc)
        self.raw_data_struc_lable = QtWidgets.QLabel(self.raw_properties)
        self.raw_data_struc_lable.setObjectName("raw_data_struc_lable")
        self.horizontalLayout_4.addWidget(self.raw_data_struc_lable)
        self.raw_data_sep = QtWidgets.QComboBox(self.raw_properties)
        self.raw_data_sep.setObjectName("raw_data_sep")
        self.horizontalLayout_4.addWidget(self.raw_data_sep)
        self.raw_data_sep_lable = QtWidgets.QLabel(self.raw_properties)
        self.raw_data_sep_lable.setObjectName("raw_data_sep_lable")
        self.horizontalLayout_4.addWidget(self.raw_data_sep_lable)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.widget_22 = QtWidgets.QWidget(self.raw_properties)
        self.widget_22.setObjectName("widget_22")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.widget_22)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.raw_x_fac = QtWidgets.QDoubleSpinBox(self.widget_22)
        self.raw_x_fac.setDecimals(4)
        self.raw_x_fac.setMinimum(-1000000.0)
        self.raw_x_fac.setMaximum(1000000.0)
        self.raw_x_fac.setProperty("value", 1.0)
        self.raw_x_fac.setObjectName("raw_x_fac")
        self.horizontalLayout_19.addWidget(self.raw_x_fac)
        self.label_17 = QtWidgets.QLabel(self.widget_22)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_19.addWidget(self.label_17)
        self.raw_y_fac = QtWidgets.QDoubleSpinBox(self.widget_22)
        self.raw_y_fac.setDecimals(4)
        self.raw_y_fac.setMinimum(-1000000.0)
        self.raw_y_fac.setMaximum(1000000.0)
        self.raw_y_fac.setSingleStep(1.0)
        self.raw_y_fac.setProperty("value", 1.0)
        self.raw_y_fac.setObjectName("raw_y_fac")
        self.horizontalLayout_19.addWidget(self.raw_y_fac)
        self.label_18 = QtWidgets.QLabel(self.widget_22)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_19.addWidget(self.label_18)
        self.raw_z_fac = QtWidgets.QDoubleSpinBox(self.widget_22)
        self.raw_z_fac.setDecimals(4)
        self.raw_z_fac.setMinimum(-1000000.0)
        self.raw_z_fac.setMaximum(1000000.0)
        self.raw_z_fac.setObjectName("raw_z_fac")
        self.horizontalLayout_19.addWidget(self.raw_z_fac)
        self.label_19 = QtWidgets.QLabel(self.widget_22)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_19.addWidget(self.label_19)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem2)
        self.verticalLayout.addWidget(self.widget_22)
        self.verticalLayout_3.addWidget(self.raw_properties)
        self.rawdatatable = QtWidgets.QTableView(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.rawdatatable.sizePolicy().hasHeightForWidth())
        self.rawdatatable.setSizePolicy(sizePolicy)
        self.rawdatatable.setObjectName("rawdatatable")
        self.verticalLayout_3.addWidget(self.rawdatatable)
        self.verticalLayout_4.addWidget(self.widget)
        self.tabWidget.addTab(self.raw_data_tab, "")
        self.interpolation_tab = QtWidgets.QWidget()
        self.interpolation_tab.setObjectName("interpolation_tab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.interpolation_tab)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget_4 = QtWidgets.QWidget(self.interpolation_tab)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.widget_3 = QtWidgets.QWidget(self.widget_4)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_2 = QtWidgets.QWidget(self.widget_3)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_10 = QtWidgets.QWidget(self.widget_2)
        self.widget_10.setObjectName("widget_10")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.widget_10)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.widget_8 = QtWidgets.QWidget(self.widget_10)
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_8)
        self.horizontalLayout_6.setContentsMargins(0, -1, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.interpolation_resolution_x = QtWidgets.QDoubleSpinBox(self.widget_8)
        self.interpolation_resolution_x.setDecimals(3)
        self.interpolation_resolution_x.setMinimum(0.001)
        self.interpolation_resolution_x.setMaximum(1000000.0)
        self.interpolation_resolution_x.setProperty("value", 1.0)
        self.interpolation_resolution_x.setObjectName("interpolation_resolution_x")
        self.horizontalLayout_6.addWidget(self.interpolation_resolution_x)
        self.label = QtWidgets.QLabel(self.widget_8)
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        self.verticalLayout_10.addWidget(self.widget_8)
        self.widget_9 = QtWidgets.QWidget(self.widget_10)
        self.widget_9.setObjectName("widget_9")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_9)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.interpolation_resolution_y = QtWidgets.QDoubleSpinBox(self.widget_9)
        self.interpolation_resolution_y.setDecimals(3)
        self.interpolation_resolution_y.setMinimum(0.001)
        self.interpolation_resolution_y.setMaximum(1000000.0)
        self.interpolation_resolution_y.setProperty("value", 1.0)
        self.interpolation_resolution_y.setObjectName("interpolation_resolution_y")
        self.horizontalLayout_7.addWidget(self.interpolation_resolution_y)
        self.label_4 = QtWidgets.QLabel(self.widget_9)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_7.addWidget(self.label_4)
        self.verticalLayout_10.addWidget(self.widget_9)
        self.horizontalLayout.addWidget(self.widget_10)
        self.interpolation_method = QtWidgets.QComboBox(self.widget_2)
        self.interpolation_method.setObjectName("interpolation_method")
        self.horizontalLayout.addWidget(self.interpolation_method)
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.interpolation_interpolate = QtWidgets.QPushButton(self.widget_2)
        self.interpolation_interpolate.setObjectName("interpolation_interpolate")
        self.horizontalLayout.addWidget(self.interpolation_interpolate)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.widget_5 = QtWidgets.QWidget(self.widget_3)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.interpolation_save = QtWidgets.QPushButton(self.widget_5)
        self.interpolation_save.setObjectName("interpolation_save")
        self.horizontalLayout_2.addWidget(self.interpolation_save)
        self.verticalLayout_2.addWidget(self.widget_5)
        self.verticalLayout_6.addWidget(self.widget_3)
        self.verticalLayout_5.addWidget(self.widget_4)
        self.interpolation_data_table = QtWidgets.QTableView(self.interpolation_tab)
        self.interpolation_data_table.setObjectName("interpolation_data_table")
        self.verticalLayout_5.addWidget(self.interpolation_data_table)
        self.tabWidget.addTab(self.interpolation_tab, "")
        self.correction_tab = QtWidgets.QWidget()
        self.correction_tab.setObjectName("correction_tab")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.correction_tab)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.scrollArea = QtWidgets.QScrollArea(self.correction_tab)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 729, 1339))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_9.addWidget(self.label_5)
        self.widget_6 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_6.setEnabled(True)
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_5.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.widget_6)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.correction_raw_plottype_contour = QtWidgets.QRadioButton(self.widget_6)
        self.correction_raw_plottype_contour.setObjectName("correction_raw_plottype_contour")
        self.horizontalLayout_5.addWidget(self.correction_raw_plottype_contour)
        self.correction_raw_plottype_mesh = QtWidgets.QRadioButton(self.widget_6)
        self.correction_raw_plottype_mesh.setObjectName("correction_raw_plottype_mesh")
        self.horizontalLayout_5.addWidget(self.correction_raw_plottype_mesh)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.verticalLayout_9.addWidget(self.widget_6)
        self.coorection_top_image_widget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.coorection_top_image_widget.setMinimumSize(QtCore.QSize(0, 300))
        self.coorection_top_image_widget.setObjectName("coorection_top_image_widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.coorection_top_image_widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_9.addWidget(self.coorection_top_image_widget)
        self.widget_21 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_21.setObjectName("widget_21")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.widget_21)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem6)
        self.interpolation_addcorner_button = QtWidgets.QPushButton(self.widget_21)
        self.interpolation_addcorner_button.setObjectName("interpolation_addcorner_button")
        self.horizontalLayout_18.addWidget(self.interpolation_addcorner_button)
        self.interpolation_clear_button = QtWidgets.QPushButton(self.widget_21)
        self.interpolation_clear_button.setObjectName("interpolation_clear_button")
        self.horizontalLayout_18.addWidget(self.interpolation_clear_button)
        self.verticalLayout_9.addWidget(self.widget_21)
        self.correntionpoint_table = QtWidgets.QTableWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.correntionpoint_table.sizePolicy().hasHeightForWidth())
        self.correntionpoint_table.setSizePolicy(sizePolicy)
        self.correntionpoint_table.setMinimumSize(QtCore.QSize(0, 200))
        self.correntionpoint_table.setObjectName("correntionpoint_table")
        self.correntionpoint_table.setColumnCount(0)
        self.correntionpoint_table.setRowCount(0)
        self.verticalLayout_9.addWidget(self.correntionpoint_table)
        self.widget_11 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_11.setObjectName("widget_11")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_11)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem7)
        self.correction_spin_cut_lower = QtWidgets.QDoubleSpinBox(self.widget_11)
        self.correction_spin_cut_lower.setMaximum(100.0)
        self.correction_spin_cut_lower.setObjectName("correction_spin_cut_lower")
        self.horizontalLayout_8.addWidget(self.correction_spin_cut_lower)
        self.label_16 = QtWidgets.QLabel(self.widget_11)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_8.addWidget(self.label_16)
        self.correction_spin_cut_upper = QtWidgets.QDoubleSpinBox(self.widget_11)
        self.correction_spin_cut_upper.setMaximum(100.0)
        self.correction_spin_cut_upper.setObjectName("correction_spin_cut_upper")
        self.horizontalLayout_8.addWidget(self.correction_spin_cut_upper)
        self.label_15 = QtWidgets.QLabel(self.widget_11)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_8.addWidget(self.label_15)
        self.update_correction_button = QtWidgets.QPushButton(self.widget_11)
        self.update_correction_button.setObjectName("update_correction_button")
        self.horizontalLayout_8.addWidget(self.update_correction_button)
        self.verticalLayout_9.addWidget(self.widget_11)
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_9.addWidget(self.label_6)
        self.correction_surface_view = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.correction_surface_view.setMinimumSize(QtCore.QSize(0, 300))
        self.correction_surface_view.setObjectName("correction_surface_view")
        self.gridLayout = QtWidgets.QGridLayout(self.correction_surface_view)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_9.addWidget(self.correction_surface_view)
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_9.addWidget(self.label_7)
        self.correcte_data_plot = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.correcte_data_plot.setMinimumSize(QtCore.QSize(0, 200))
        self.correcte_data_plot.setObjectName("correcte_data_plot")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.correcte_data_plot)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_9.addWidget(self.correcte_data_plot)
        self.widget_7 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout_9.addWidget(self.widget_7)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_8.addWidget(self.scrollArea)
        self.tabWidget.addTab(self.correction_tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab3d = QtWidgets.QWidget()
        self.tab3d.setObjectName("tab3d")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.tab3d)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.widget_12 = QtWidgets.QWidget(self.tab3d)
        self.widget_12.setObjectName("widget_12")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.widget_12)
        self.horizontalLayout_16.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.widget_13 = QtWidgets.QWidget(self.widget_12)
        self.widget_13.setObjectName("widget_13")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.widget_13)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.widget_14 = QtWidgets.QWidget(self.widget_13)
        self.widget_14.setObjectName("widget_14")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.widget_14)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.slider_3d_camera_x = QtWidgets.QSlider(self.widget_14)
        self.slider_3d_camera_x.setMinimumSize(QtCore.QSize(200, 0))
        self.slider_3d_camera_x.setOrientation(QtCore.Qt.Horizontal)
        self.slider_3d_camera_x.setObjectName("slider_3d_camera_x")
        self.horizontalLayout_11.addWidget(self.slider_3d_camera_x)
        self.label_10 = QtWidgets.QLabel(self.widget_14)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_11.addWidget(self.label_10)
        self.verticalLayout_12.addWidget(self.widget_14)
        self.widget_16 = QtWidgets.QWidget(self.widget_13)
        self.widget_16.setObjectName("widget_16")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.widget_16)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.slider_3d_camera_y = QtWidgets.QSlider(self.widget_16)
        self.slider_3d_camera_y.setOrientation(QtCore.Qt.Horizontal)
        self.slider_3d_camera_y.setObjectName("slider_3d_camera_y")
        self.horizontalLayout_10.addWidget(self.slider_3d_camera_y)
        self.label_9 = QtWidgets.QLabel(self.widget_16)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_10.addWidget(self.label_9)
        self.verticalLayout_12.addWidget(self.widget_16)
        self.widget_15 = QtWidgets.QWidget(self.widget_13)
        self.widget_15.setObjectName("widget_15")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget_15)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.slider_3d_camera_z = QtWidgets.QSlider(self.widget_15)
        self.slider_3d_camera_z.setOrientation(QtCore.Qt.Horizontal)
        self.slider_3d_camera_z.setObjectName("slider_3d_camera_z")
        self.horizontalLayout_9.addWidget(self.slider_3d_camera_z)
        self.label_11 = QtWidgets.QLabel(self.widget_15)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_9.addWidget(self.label_11)
        self.verticalLayout_12.addWidget(self.widget_15)
        self.horizontalLayout_16.addWidget(self.widget_13)
        self.widget_17 = QtWidgets.QWidget(self.widget_12)
        self.widget_17.setObjectName("widget_17")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.widget_17)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.widget_18 = QtWidgets.QWidget(self.widget_17)
        self.widget_18.setObjectName("widget_18")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.widget_18)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.slider_3d_distance = QtWidgets.QSlider(self.widget_18)
        self.slider_3d_distance.setMinimumSize(QtCore.QSize(200, 0))
        self.slider_3d_distance.setOrientation(QtCore.Qt.Horizontal)
        self.slider_3d_distance.setObjectName("slider_3d_distance")
        self.horizontalLayout_12.addWidget(self.slider_3d_distance)
        self.label_12 = QtWidgets.QLabel(self.widget_18)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_12.addWidget(self.label_12)
        self.verticalLayout_13.addWidget(self.widget_18)
        self.widget_19 = QtWidgets.QWidget(self.widget_17)
        self.widget_19.setObjectName("widget_19")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.widget_19)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.slider_3d_azimute = QtWidgets.QSlider(self.widget_19)
        self.slider_3d_azimute.setMaximum(360)
        self.slider_3d_azimute.setOrientation(QtCore.Qt.Horizontal)
        self.slider_3d_azimute.setObjectName("slider_3d_azimute")
        self.horizontalLayout_14.addWidget(self.slider_3d_azimute)
        self.label_13 = QtWidgets.QLabel(self.widget_19)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_14.addWidget(self.label_13)
        self.verticalLayout_13.addWidget(self.widget_19)
        self.widget_20 = QtWidgets.QWidget(self.widget_17)
        self.widget_20.setObjectName("widget_20")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.widget_20)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.slider_3d_elevation = QtWidgets.QSlider(self.widget_20)
        self.slider_3d_elevation.setMinimum(-90)
        self.slider_3d_elevation.setMaximum(90)
        self.slider_3d_elevation.setOrientation(QtCore.Qt.Horizontal)
        self.slider_3d_elevation.setObjectName("slider_3d_elevation")
        self.horizontalLayout_15.addWidget(self.slider_3d_elevation)
        self.label_14 = QtWidgets.QLabel(self.widget_20)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_15.addWidget(self.label_14)
        self.verticalLayout_13.addWidget(self.widget_20)
        self.horizontalLayout_16.addWidget(self.widget_17)
        spacerItem8 = QtWidgets.QSpacerItem(129, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem8)
        self.label_8 = QtWidgets.QLabel(self.widget_12)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_16.addWidget(self.label_8)
        self.plot3d_data_source = QtWidgets.QComboBox(self.widget_12)
        self.plot3d_data_source.setObjectName("plot3d_data_source")
        self.horizontalLayout_16.addWidget(self.plot3d_data_source)
        self.verticalLayout_11.addWidget(self.widget_12)
        self.widget_23 = QtWidgets.QWidget(self.tab3d)
        self.widget_23.setObjectName("widget_23")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.widget_23)
        self.horizontalLayout_21.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.scale_3d_x = QtWidgets.QDoubleSpinBox(self.widget_23)
        self.scale_3d_x.setMinimum(-1000.0)
        self.scale_3d_x.setMaximum(1000.0)
        self.scale_3d_x.setSingleStep(0.1)
        self.scale_3d_x.setProperty("value", 1.0)
        self.scale_3d_x.setObjectName("scale_3d_x")
        self.horizontalLayout_21.addWidget(self.scale_3d_x)
        self.label_23 = QtWidgets.QLabel(self.widget_23)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_21.addWidget(self.label_23)
        self.scale_3d_y = QtWidgets.QDoubleSpinBox(self.widget_23)
        self.scale_3d_y.setMinimum(-1000.0)
        self.scale_3d_y.setMaximum(1000.0)
        self.scale_3d_y.setSingleStep(0.1)
        self.scale_3d_y.setProperty("value", 1.0)
        self.scale_3d_y.setObjectName("scale_3d_y")
        self.horizontalLayout_21.addWidget(self.scale_3d_y)
        self.label_24 = QtWidgets.QLabel(self.widget_23)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_21.addWidget(self.label_24)
        self.scale_3d_z = QtWidgets.QDoubleSpinBox(self.widget_23)
        self.scale_3d_z.setMinimum(-1000.0)
        self.scale_3d_z.setMaximum(1000.0)
        self.scale_3d_z.setSingleStep(0.1)
        self.scale_3d_z.setProperty("value", 1.0)
        self.scale_3d_z.setObjectName("scale_3d_z")
        self.horizontalLayout_21.addWidget(self.scale_3d_z)
        self.label_25 = QtWidgets.QLabel(self.widget_23)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_21.addWidget(self.label_25)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem9)
        self.verticalLayout_11.addWidget(self.widget_23)
        self.legend3d_widget = QtWidgets.QWidget(self.tab3d)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.legend3d_widget.sizePolicy().hasHeightForWidth())
        self.legend3d_widget.setSizePolicy(sizePolicy)
        self.legend3d_widget.setMinimumSize(QtCore.QSize(0, 100))
        self.legend3d_widget.setMaximumSize(QtCore.QSize(16777215, 100))
        self.legend3d_widget.setObjectName("legend3d_widget")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.legend3d_widget)
        self.horizontalLayout_17.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.verticalLayout_11.addWidget(self.legend3d_widget)
        self.plot3d_pot_widget = QtWidgets.QWidget(self.tab3d)
        self.plot3d_pot_widget.setAutoFillBackground(False)
        self.plot3d_pot_widget.setObjectName("plot3d_pot_widget")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.plot3d_pot_widget)
        self.horizontalLayout_13.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_13.addItem(spacerItem10)
        self.verticalLayout_11.addWidget(self.plot3d_pot_widget)
        self.tabWidget.addTab(self.tab3d, "")
        self.verticalLayout_7.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.mainWidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 815, 31))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.raw_file_path.setText(_translate("MainWindow", "test"))
        self.raw_load_button.setText(_translate("MainWindow", "load"))
        self.raw_search_button.setText(_translate("MainWindow", "search"))
        self.raw_data_struc_lable.setText(_translate("MainWindow", "raw data structure"))
        self.raw_data_sep_lable.setText(_translate("MainWindow", "raw data separator"))
        self.label_17.setText(_translate("MainWindow", "x fac"))
        self.label_18.setText(_translate("MainWindow", "y fac"))
        self.label_19.setText(_translate("MainWindow", "z fac"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.raw_data_tab), _translate("MainWindow", "raw data"))
        self.label.setText(_translate("MainWindow", "Xresolution"))
        self.label_4.setText(_translate("MainWindow", "Yresolution"))
        self.label_2.setText(_translate("MainWindow", "method"))
        self.interpolation_interpolate.setText(_translate("MainWindow", "interpolate raw"))
        self.interpolation_save.setText(_translate("MainWindow", "save"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.interpolation_tab), _translate("MainWindow", "interpolation"))
        self.label_5.setText(_translate("MainWindow", "Interpolated Data"))
        self.label_3.setText(_translate("MainWindow", "plot type"))
        self.correction_raw_plottype_contour.setText(_translate("MainWindow", "contour"))
        self.correction_raw_plottype_mesh.setText(_translate("MainWindow", "mesh"))
        self.interpolation_addcorner_button.setText(_translate("MainWindow", "add corners"))
        self.interpolation_clear_button.setText(_translate("MainWindow", "clear"))
        self.label_16.setText(_translate("MainWindow", "cut lower"))
        self.label_15.setText(_translate("MainWindow", "cut upper"))
        self.update_correction_button.setText(_translate("MainWindow", "update"))
        self.label_6.setText(_translate("MainWindow", "Correction Surface"))
        self.label_7.setText(_translate("MainWindow", "Corrected Data Plot"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.correction_tab), _translate("MainWindow", "correction"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Scratch"))
        self.label_10.setText(_translate("MainWindow", "camera x"))
        self.label_9.setText(_translate("MainWindow", "camera y"))
        self.label_11.setText(_translate("MainWindow", "camera z"))
        self.label_12.setText(_translate("MainWindow", "distance"))
        self.label_13.setText(_translate("MainWindow", "azimute"))
        self.label_14.setText(_translate("MainWindow", "elevation"))
        self.label_8.setText(_translate("MainWindow", "data"))
        self.label_23.setText(_translate("MainWindow", "X scale"))
        self.label_24.setText(_translate("MainWindow", "y scale"))
        self.label_25.setText(_translate("MainWindow", "z scale"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab3d), _translate("MainWindow", "3D"))

